version: '3'

silent: true

tasks:

  build:
    desc: Builds the library in debug mode
    cmds:
      - cmd: cargo build

  clean:
    desc: Cleans all targets
    cmds:
      - cmd: cargo clean

  clippy:
    desc: Runs clippy for all targets
    cmds:
      - cmd: cargo +nightly clippy --all-targets

  doc-open:
    desc: Generates the documentation and opens it in the browser
    cmds:
      - cmd: cargo doc --no-deps --open

  doc:
    desc: Generates the documentation
    cmds:
      - cmd: cargo doc --no-deps

  fmt:
    desc: Runs the code formatter
    cmds:
      - cmd: cargo +nightly fmt

  release:
    desc: Builds the library in release mode
    cmds:
      - cmd: cargo clean
      - cmd: cargo +stable build --release

  test:
    desc: Tests the library in debug mode
    cmds:
      - cmd: cargo +nightly test
