use std::fmt;
use std::fmt::Display;

/// CSS colors.
#[derive(Debug, Copy, Clone)]
pub enum CssColor {
  AliceBlue,
  AntiqueWhite,
  Aqua,
  Aquamarine,
  Azure,
  Beige,
  Bisque,
  Black,
  BlanchedAlmond,
  Blue,
  BlueViolet,
  Brown,
  BurlyWood,
  CadetBlue,
  Chartreuse,
  Chocolate,
  Coral,
  CornflowerBlue,
  Cornsilk,
  Crimson,
  Cyan,
  DarkBlue,
  DarkCyan,
  DarkGoldenRod,
  DarkGray,
  DarkGreen,
  DarkGrey,
  DarkKhaki,
  DarkMagenta,
  DarkOliveGreen,
  DarkOrange,
  DarkOrchid,
  DarkRed,
  DarkSalmon,
  DarkSeaGreen,
  DarkSlateBlue,
  DarkSlateGray,
  DarkSlateGrey,
  DarkTurquoise,
  DarkViolet,
  DeepPink,
  DeepSkyBlue,
  DimGray,
  DimGrey,
  DodgerBlue,
  FireBrick,
  FloralWhite,
  ForestGreen,
  Fuchsia,
  Gainsboro,
  GhostWhite,
  Gold,
  GoldenRod,
  Gray,
  Green,
  GreenYellow,
  Grey,
  HoneyDew,
  HotPink,
  IndianRed,
  Indigo,
  Ivory,
  Khaki,
  Lavender,
  LavenderBlush,
  LawnGreen,
  LemonChiffon,
  LightBlue,
  LightCoral,
  LightCyan,
  LightGoldenRodYellow,
  LightGray,
  LightGreen,
  LightGrey,
  LightPink,
  LightSalmon,
  LightSeaGreen,
  LightSkyBlue,
  LightSlateGray,
  LightSlateGrey,
  LightSteelBlue,
  LightYellow,
  Lime,
  LimeGreen,
  Linen,
  Magenta,
  Maroon,
  MediumAquaMarine,
  MediumBlue,
  MediumOrchid,
  MediumPurple,
  MediumSeaGreen,
  MediumSlateBlue,
  MediumSpringGreen,
  MediumTurquoise,
  MediumVioletRed,
  MidnightBlue,
  MintCream,
  MistyRose,
  Moccasin,
  NavajoWhite,
  Navy,
  OldLace,
  Olive,
  OliveDrab,
  Orange,
  OrangeRed,
  Orchid,
  PaleGoldenRod,
  PaleGreen,
  PaleTurquoise,
  PaleVioletRed,
  PapayaWhip,
  PeachPuff,
  Peru,
  Pink,
  Plum,
  PowderBlue,
  Purple,
  RebeccaPurple,
  Red,
  RosyBrown,
  RoyalBlue,
  SaddleBrown,
  Salmon,
  SandyBrown,
  SeaGreen,
  SeaShell,
  Sienna,
  Silver,
  SkyBlue,
  SlateBlue,
  SlateGray,
  SlateGrey,
  Snow,
  SpringGreen,
  SteelBlue,
  Tan,
  Teal,
  Thistle,
  Tomato,
  Transparent,
  Turquoise,
  Violet,
  Wheat,
  White,
  WhiteSmoke,
  Yellow,
  YellowGreen,
  Hex(u32),
}

impl Display for CssColor {
  fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
    write!(
      f,
      "{}",
      match self {
        CssColor::AliceBlue => "aliceblue".to_string(),
        CssColor::AntiqueWhite => "antiquewhite".to_string(),
        CssColor::Aqua => "aqua".to_string(),
        CssColor::Aquamarine => "aquamarine".to_string(),
        CssColor::Azure => "azure".to_string(),
        CssColor::Beige => "beige".to_string(),
        CssColor::Bisque => "bisque".to_string(),
        CssColor::Black => "black".to_string(),
        CssColor::BlanchedAlmond => "blanchedalmond".to_string(),
        CssColor::Blue => "blue".to_string(),
        CssColor::BlueViolet => "blueviolet".to_string(),
        CssColor::Brown => "brown".to_string(),
        CssColor::BurlyWood => "burlywood".to_string(),
        CssColor::CadetBlue => "cadetblue".to_string(),
        CssColor::Chartreuse => "chartreuse".to_string(),
        CssColor::Chocolate => "chocolate".to_string(),
        CssColor::Coral => "coral".to_string(),
        CssColor::CornflowerBlue => "cornflowerblue".to_string(),
        CssColor::Cornsilk => "cornsilk".to_string(),
        CssColor::Crimson => "crimson".to_string(),
        CssColor::Cyan => "cyan".to_string(),
        CssColor::DarkBlue => "darkblue".to_string(),
        CssColor::DarkCyan => "darkcyan".to_string(),
        CssColor::DarkGoldenRod => "darkgoldenrod".to_string(),
        CssColor::DarkGray => "darkgray".to_string(),
        CssColor::DarkGreen => "darkgreen".to_string(),
        CssColor::DarkGrey => "darkgrey".to_string(),
        CssColor::DarkKhaki => "darkkhaki".to_string(),
        CssColor::DarkMagenta => "darkmagenta".to_string(),
        CssColor::DarkOliveGreen => "darkolivegreen".to_string(),
        CssColor::DarkOrange => "darkorange".to_string(),
        CssColor::DarkOrchid => "darkorchid".to_string(),
        CssColor::DarkRed => "darkred".to_string(),
        CssColor::DarkSalmon => "darksalmon".to_string(),
        CssColor::DarkSeaGreen => "darkseagreen".to_string(),
        CssColor::DarkSlateBlue => "darkslateblue".to_string(),
        CssColor::DarkSlateGray => "darkslategray".to_string(),
        CssColor::DarkSlateGrey => "darkslategrey".to_string(),
        CssColor::DarkTurquoise => "darkturquoise".to_string(),
        CssColor::DarkViolet => "darkviolet".to_string(),
        CssColor::DeepPink => "deeppink".to_string(),
        CssColor::DeepSkyBlue => "deepskyblue".to_string(),
        CssColor::DimGray => "dimgray".to_string(),
        CssColor::DimGrey => "dimgrey".to_string(),
        CssColor::DodgerBlue => "dodgerblue".to_string(),
        CssColor::FireBrick => "firebrick".to_string(),
        CssColor::FloralWhite => "floralwhite".to_string(),
        CssColor::ForestGreen => "forestgreen".to_string(),
        CssColor::Fuchsia => "fuchsia".to_string(),
        CssColor::Gainsboro => "gainsboro".to_string(),
        CssColor::GhostWhite => "ghostwhite".to_string(),
        CssColor::Gold => "gold".to_string(),
        CssColor::GoldenRod => "goldenrod".to_string(),
        CssColor::Gray => "gray".to_string(),
        CssColor::Green => "green".to_string(),
        CssColor::GreenYellow => "greenyellow".to_string(),
        CssColor::Grey => "grey".to_string(),
        CssColor::HoneyDew => "honeydew".to_string(),
        CssColor::HotPink => "hotpink".to_string(),
        CssColor::IndianRed => "indianred".to_string(),
        CssColor::Indigo => "indigo".to_string(),
        CssColor::Ivory => "ivory".to_string(),
        CssColor::Khaki => "khaki".to_string(),
        CssColor::Lavender => "lavender".to_string(),
        CssColor::LavenderBlush => "lavenderblush".to_string(),
        CssColor::LawnGreen => "lawngreen".to_string(),
        CssColor::LemonChiffon => "lemonchiffon".to_string(),
        CssColor::LightBlue => "lightblue".to_string(),
        CssColor::LightCoral => "lightcoral".to_string(),
        CssColor::LightCyan => "lightcyan".to_string(),
        CssColor::LightGoldenRodYellow => "lightgoldenrodyellow".to_string(),
        CssColor::LightGray => "lightgray".to_string(),
        CssColor::LightGreen => "lightgreen".to_string(),
        CssColor::LightGrey => "lightgrey".to_string(),
        CssColor::LightPink => "lightpink".to_string(),
        CssColor::LightSalmon => "lightsalmon".to_string(),
        CssColor::LightSeaGreen => "lightseagreen".to_string(),
        CssColor::LightSkyBlue => "lightskyblue".to_string(),
        CssColor::LightSlateGray => "lightslategray".to_string(),
        CssColor::LightSlateGrey => "lightslategrey".to_string(),
        CssColor::LightSteelBlue => "lightsteelblue".to_string(),
        CssColor::LightYellow => "lightyellow".to_string(),
        CssColor::Lime => "lime".to_string(),
        CssColor::LimeGreen => "limegreen".to_string(),
        CssColor::Linen => "linen".to_string(),
        CssColor::Magenta => "magenta".to_string(),
        CssColor::Maroon => "maroon".to_string(),
        CssColor::MediumAquaMarine => "mediumaquamarine".to_string(),
        CssColor::MediumBlue => "mediumblue".to_string(),
        CssColor::MediumOrchid => "mediumorchid".to_string(),
        CssColor::MediumPurple => "mediumpurple".to_string(),
        CssColor::MediumSeaGreen => "mediumseagreen".to_string(),
        CssColor::MediumSlateBlue => "mediumslateblue".to_string(),
        CssColor::MediumSpringGreen => "mediumspringgreen".to_string(),
        CssColor::MediumTurquoise => "mediumturquoise".to_string(),
        CssColor::MediumVioletRed => "mediumvioletred".to_string(),
        CssColor::MidnightBlue => "midnightblue".to_string(),
        CssColor::MintCream => "mintcream".to_string(),
        CssColor::MistyRose => "mistyrose".to_string(),
        CssColor::Moccasin => "moccasin".to_string(),
        CssColor::NavajoWhite => "navajowhite".to_string(),
        CssColor::Navy => "navy".to_string(),
        CssColor::OldLace => "oldlace".to_string(),
        CssColor::Olive => "olive".to_string(),
        CssColor::OliveDrab => "olivedrab".to_string(),
        CssColor::Orange => "orange".to_string(),
        CssColor::OrangeRed => "orangered".to_string(),
        CssColor::Orchid => "orchid".to_string(),
        CssColor::PaleGoldenRod => "palegoldenrod".to_string(),
        CssColor::PaleGreen => "palegreen".to_string(),
        CssColor::PaleTurquoise => "paleturquoise".to_string(),
        CssColor::PaleVioletRed => "palevioletred".to_string(),
        CssColor::PapayaWhip => "papayawhip".to_string(),
        CssColor::PeachPuff => "peachpuff".to_string(),
        CssColor::Peru => "peru".to_string(),
        CssColor::Pink => "pink".to_string(),
        CssColor::Plum => "plum".to_string(),
        CssColor::PowderBlue => "powderblue".to_string(),
        CssColor::Purple => "purple".to_string(),
        CssColor::RebeccaPurple => "rebeccapurple".to_string(),
        CssColor::Red => "red".to_string(),
        CssColor::RosyBrown => "rosybrown".to_string(),
        CssColor::RoyalBlue => "royalblue".to_string(),
        CssColor::SaddleBrown => "saddlebrown".to_string(),
        CssColor::Salmon => "salmon".to_string(),
        CssColor::SandyBrown => "sandybrown".to_string(),
        CssColor::SeaGreen => "seagreen".to_string(),
        CssColor::SeaShell => "seashell".to_string(),
        CssColor::Sienna => "sienna".to_string(),
        CssColor::Silver => "silver".to_string(),
        CssColor::SkyBlue => "skyblue".to_string(),
        CssColor::SlateBlue => "slateblue".to_string(),
        CssColor::SlateGray => "slategray".to_string(),
        CssColor::SlateGrey => "slategrey".to_string(),
        CssColor::Snow => "snow".to_string(),
        CssColor::SpringGreen => "springgreen".to_string(),
        CssColor::SteelBlue => "steelblue".to_string(),
        CssColor::Tan => "tan".to_string(),
        CssColor::Teal => "teal".to_string(),
        CssColor::Thistle => "thistle".to_string(),
        CssColor::Tomato => "tomato".to_string(),
        CssColor::Transparent => "transparent".to_string(),
        CssColor::Turquoise => "turquoise".to_string(),
        CssColor::Violet => "violet".to_string(),
        CssColor::Wheat => "wheat".to_string(),
        CssColor::White => "white".to_string(),
        CssColor::WhiteSmoke => "whitesmoke".to_string(),
        CssColor::Yellow => "yellow".to_string(),
        CssColor::YellowGreen => "yellowgreen".to_string(),
        CssColor::Hex(value) => format!("#{:06X}", value & 0xFFFFFF),
      }
    )
  }
}
