use std::fmt;
use std::fmt::Display;

/// CSS colors.
#[derive(Copy, Clone)]
pub enum CssColor {
  Black,
  Navy,
  DarkBlue,
  MediumBlue,
  Blue,
  DarkGreen,
  Green,
  Teal,
  DarkCyan,
  DeepSkyBlue,
  DarkTurquoise,
  MediumSpringGreen,
  Lime,
  SpringGreen,
  Aqua,
  Cyan,
  MidnightBlue,
  DodgerBlue,
  LightSeaGreen,
  ForestGreen,
  SeaGreen,
  DarkSlateGray,
  DarkSlateGrey,
  LimeGreen,
  MediumSeaGreen,
  Turquoise,
  RoyalBlue,
  SteelBlue,
  DarkSlateBlue,
  MediumTurquoise,
  Indigo,
  DarkOliveGreen,
  CadetBlue,
  CornflowerBlue,
  RebeccaPurple,
  MediumAquaMarine,
  DimGray,
  DimGrey,
  SlateBlue,
  OliveDrab,
  SlateGray,
  SlateGrey,
  LightSlateGray,
  LightSlateGrey,
  MediumSlateBlue,
  LawnGreen,
  Chartreuse,
  Aquamarine,
  Maroon,
  Purple,
  Olive,
  Gray,
  Grey,
  SkyBlue,
  LightSkyBlue,
  BlueViolet,
  DarkRed,
  DarkMagenta,
  SaddleBrown,
  DarkSeaGreen,
  LightGreen,
  MediumPurple,
  DarkViolet,
  PaleGreen,
  DarkOrchid,
  YellowGreen,
  Sienna,
  Brown,
  DarkGray,
  DarkGrey,
  LightBlue,
  GreenYellow,
  PaleTurquoise,
  LightSteelBlue,
  PowderBlue,
  FireBrick,
  DarkGoldenRod,
  MediumOrchid,
  RosyBrown,
  DarkKhaki,
  Silver,
  MediumVioletRed,
  IndianRed,
  Peru,
  Chocolate,
  Tan,
  LightGray,
  LightGrey,
  Thistle,
  Orchid,
  GoldenRod,
  PaleVioletRed,
  Crimson,
  Gainsboro,
  Plum,
  BurlyWood,
  LightCyan,
  Lavender,
  DarkSalmon,
  Violet,
  PaleGoldenRod,
  LightCoral,
  Khaki,
  AliceBlue,
  HoneyDew,
  Azure,
  SandyBrown,
  Wheat,
  Beige,
  WhiteSmoke,
  MintCream,
  GhostWhite,
  Salmon,
  AntiqueWhite,
  Linen,
  LightGoldenRodYellow,
  OldLace,
  Red,
  Fuchsia,
  Magenta,
  DeepPink,
  OrangeRed,
  Tomato,
  HotPink,
  Coral,
  DarkOrange,
  LightSalmon,
  Orange,
  LightPink,
  Pink,
  Gold,
  PeachPuff,
  NavajoWhite,
  Moccasin,
  Bisque,
  MistyRose,
  BlanchedAlmond,
  PapayaWhip,
  LavenderBlush,
  SeaShell,
  Cornsilk,
  LemonChiffon,
  FloralWhite,
  Snow,
  Yellow,
  LightYellow,
  Ivory,
  White,
  Hex(u32),
}

impl Display for CssColor {
  fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
    write!(
      f,
      "{}",
      match self {
        CssColor::Black => "#000000".to_string(),
        CssColor::Navy => "#000080".to_string(),
        CssColor::DarkBlue => "#00008B".to_string(),
        CssColor::MediumBlue => "#0000CD".to_string(),
        CssColor::Blue => "#0000FF".to_string(),
        CssColor::DarkGreen => "#006400".to_string(),
        CssColor::Green => "#008000".to_string(),
        CssColor::Teal => "#008080".to_string(),
        CssColor::DarkCyan => "#008B8B".to_string(),
        CssColor::DeepSkyBlue => "#00BFFF".to_string(),
        CssColor::DarkTurquoise => "#00CED1".to_string(),
        CssColor::MediumSpringGreen => "#00FA9A".to_string(),
        CssColor::Lime => "#00FF00".to_string(),
        CssColor::SpringGreen => "#00FF7F".to_string(),
        CssColor::Aqua => "#00FFFF".to_string(),
        CssColor::Cyan => "#00FFFF".to_string(),
        CssColor::MidnightBlue => "#191970".to_string(),
        CssColor::DodgerBlue => "#1E90FF".to_string(),
        CssColor::LightSeaGreen => "#20B2AA".to_string(),
        CssColor::ForestGreen => "#228B22".to_string(),
        CssColor::SeaGreen => "#2E8B57".to_string(),
        CssColor::DarkSlateGray => "#2F4F4F".to_string(),
        CssColor::DarkSlateGrey => "#2F4F4F".to_string(),
        CssColor::LimeGreen => "#32CD32".to_string(),
        CssColor::MediumSeaGreen => "#3CB371".to_string(),
        CssColor::Turquoise => "#40E0D0".to_string(),
        CssColor::RoyalBlue => "#4169E1".to_string(),
        CssColor::SteelBlue => "#4682B4".to_string(),
        CssColor::DarkSlateBlue => "#483D8B".to_string(),
        CssColor::MediumTurquoise => "#48D1CC".to_string(),
        CssColor::Indigo => "#4B0082".to_string(),
        CssColor::DarkOliveGreen => "#556B2F".to_string(),
        CssColor::CadetBlue => "#5F9EA0".to_string(),
        CssColor::CornflowerBlue => "#6495ED".to_string(),
        CssColor::RebeccaPurple => "#663399".to_string(),
        CssColor::MediumAquaMarine => "#66CDAA".to_string(),
        CssColor::DimGray => "#696969".to_string(),
        CssColor::DimGrey => "#696969".to_string(),
        CssColor::SlateBlue => "#6A5ACD".to_string(),
        CssColor::OliveDrab => "#6B8E23".to_string(),
        CssColor::SlateGray => "#708090".to_string(),
        CssColor::SlateGrey => "#708090".to_string(),
        CssColor::LightSlateGray => "#778899".to_string(),
        CssColor::LightSlateGrey => "#778899".to_string(),
        CssColor::MediumSlateBlue => "#7B68EE".to_string(),
        CssColor::LawnGreen => "#7CFC00".to_string(),
        CssColor::Chartreuse => "#7FFF00".to_string(),
        CssColor::Aquamarine => "#7FFFD4".to_string(),
        CssColor::Maroon => "#800000".to_string(),
        CssColor::Purple => "#800080".to_string(),
        CssColor::Olive => "#808000".to_string(),
        CssColor::Gray => "#808080".to_string(),
        CssColor::Grey => "#808080".to_string(),
        CssColor::SkyBlue => "#87CEEB".to_string(),
        CssColor::LightSkyBlue => "#87CEFA".to_string(),
        CssColor::BlueViolet => "#8A2BE2".to_string(),
        CssColor::DarkRed => "#8B0000".to_string(),
        CssColor::DarkMagenta => "#8B008B".to_string(),
        CssColor::SaddleBrown => "#8B4513".to_string(),
        CssColor::DarkSeaGreen => "#8FBC8F".to_string(),
        CssColor::LightGreen => "#90EE90".to_string(),
        CssColor::MediumPurple => "#9370DB".to_string(),
        CssColor::DarkViolet => "#9400D3".to_string(),
        CssColor::PaleGreen => "#98FB98".to_string(),
        CssColor::DarkOrchid => "#9932CC".to_string(),
        CssColor::YellowGreen => "#9ACD32".to_string(),
        CssColor::Sienna => "#A0522D".to_string(),
        CssColor::Brown => "#A52A2A".to_string(),
        CssColor::DarkGray => "#A9A9A9".to_string(),
        CssColor::DarkGrey => "#A9A9A9".to_string(),
        CssColor::LightBlue => "#ADD8E6".to_string(),
        CssColor::GreenYellow => "#ADFF2F".to_string(),
        CssColor::PaleTurquoise => "#AFEEEE".to_string(),
        CssColor::LightSteelBlue => "#B0C4DE".to_string(),
        CssColor::PowderBlue => "#B0E0E6".to_string(),
        CssColor::FireBrick => "#B22222".to_string(),
        CssColor::DarkGoldenRod => "#B8860B".to_string(),
        CssColor::MediumOrchid => "#BA55D3".to_string(),
        CssColor::RosyBrown => "#BC8F8F".to_string(),
        CssColor::DarkKhaki => "#BDB76B".to_string(),
        CssColor::Silver => "#C0C0C0".to_string(),
        CssColor::MediumVioletRed => "#C71585".to_string(),
        CssColor::IndianRed => "#CD5C5C".to_string(),
        CssColor::Peru => "#CD853F".to_string(),
        CssColor::Chocolate => "#D2691E".to_string(),
        CssColor::Tan => "#D2B48C".to_string(),
        CssColor::LightGray => "#D3D3D3".to_string(),
        CssColor::LightGrey => "#D3D3D3".to_string(),
        CssColor::Thistle => "#D8BFD8".to_string(),
        CssColor::Orchid => "#DA70D6".to_string(),
        CssColor::GoldenRod => "#DAA520".to_string(),
        CssColor::PaleVioletRed => "#DB7093".to_string(),
        CssColor::Crimson => "#DC143C".to_string(),
        CssColor::Gainsboro => "#DCDCDC".to_string(),
        CssColor::Plum => "#DDA0DD".to_string(),
        CssColor::BurlyWood => "#DEB887".to_string(),
        CssColor::LightCyan => "#E0FFFF".to_string(),
        CssColor::Lavender => "#E6E6FA".to_string(),
        CssColor::DarkSalmon => "#E9967A".to_string(),
        CssColor::Violet => "#EE82EE".to_string(),
        CssColor::PaleGoldenRod => "#EEE8AA".to_string(),
        CssColor::LightCoral => "#F08080".to_string(),
        CssColor::Khaki => "#F0E68C".to_string(),
        CssColor::AliceBlue => "#F0F8FF".to_string(),
        CssColor::HoneyDew => "#F0FFF0".to_string(),
        CssColor::Azure => "#F0FFFF".to_string(),
        CssColor::SandyBrown => "#F4A460".to_string(),
        CssColor::Wheat => "#F5DEB3".to_string(),
        CssColor::Beige => "#F5F5DC".to_string(),
        CssColor::WhiteSmoke => "#F5F5F5".to_string(),
        CssColor::MintCream => "#F5FFFA".to_string(),
        CssColor::GhostWhite => "#F8F8FF".to_string(),
        CssColor::Salmon => "#FA8072".to_string(),
        CssColor::AntiqueWhite => "#FAEBD7".to_string(),
        CssColor::Linen => "#FAF0E6".to_string(),
        CssColor::LightGoldenRodYellow => "#FAFAD2".to_string(),
        CssColor::OldLace => "#FDF5E6".to_string(),
        CssColor::Red => "#FF0000".to_string(),
        CssColor::Fuchsia => "#FF00FF".to_string(),
        CssColor::Magenta => "#FF00FF".to_string(),
        CssColor::DeepPink => "#FF1493".to_string(),
        CssColor::OrangeRed => "#FF4500".to_string(),
        CssColor::Tomato => "#FF6347".to_string(),
        CssColor::HotPink => "#FF69B4".to_string(),
        CssColor::Coral => "#FF7F50".to_string(),
        CssColor::DarkOrange => "#FF8C00".to_string(),
        CssColor::LightSalmon => "#FFA07A".to_string(),
        CssColor::Orange => "#FFA500".to_string(),
        CssColor::LightPink => "#FFB6C1".to_string(),
        CssColor::Pink => "#FFC0CB".to_string(),
        CssColor::Gold => "#FFD700".to_string(),
        CssColor::PeachPuff => "#FFDAB9".to_string(),
        CssColor::NavajoWhite => "#FFDEAD".to_string(),
        CssColor::Moccasin => "#FFE4B5".to_string(),
        CssColor::Bisque => "#FFE4C4".to_string(),
        CssColor::MistyRose => "#FFE4E1".to_string(),
        CssColor::BlanchedAlmond => "#FFEBCD".to_string(),
        CssColor::PapayaWhip => "#FFEFD5".to_string(),
        CssColor::LavenderBlush => "#FFF0F5".to_string(),
        CssColor::SeaShell => "#FFF5EE".to_string(),
        CssColor::Cornsilk => "#FFF8DC".to_string(),
        CssColor::LemonChiffon => "#FFFACD".to_string(),
        CssColor::FloralWhite => "#FFFAF0".to_string(),
        CssColor::Snow => "#FFFAFA".to_string(),
        CssColor::Yellow => "#FFFF00".to_string(),
        CssColor::LightYellow => "#FFFFE0".to_string(),
        CssColor::Ivory => "#FFFFF0".to_string(),
        CssColor::White => "#FFFFFF".to_string(),
        CssColor::Hex(value) => format!("#{:X}", value & 0x00FFFFFF),
      }
    )
  }
}
